name: zego_uikit_prebuilt_call
description: PrebuiltCall is a full-featured call kit that provides a ready-made call invitation, voice/video chat, device detection, etc. Add a voice/video call to your app in minutes.
version: 3.2.0
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.3.0
  zego_zpns: 2.3.1+2

  http: ^0.13.4
  flutter_screenutil: ">=5.5.3+2 <5.6.1"
  flutter_vibrate: ^1.3.0
  audioplayers: ^1.0.1
  statemachine: ^3.2.0
  shared_preferences: ^2.1.0
  flutter_callkit_incoming: ^1.0.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'
  dart_code_metrics: any

flutter:
  assets:
    # call
    - assets/icons/

    # invitation
    - assets/invitation/audio/
    - assets/invitation/icons/
